.TH cafingerprint 8 "02/24/02" "OpenSCEP"
.SH NAME
cafingerprint \- displays the fingerprint of the CA certificate
.SH SYNOPSIS
.BI cafingerprint CA-cert.der
.SH DESCRIPTION
.B cafingerprint
retrieves the CA subject key identifier from the CA certificate
specified by its DER filename on the command line and displays 
it on standard output.

.SH VERSION
This page documents
.B cafingerprint
as it appears in version 0.4.1 of OpenSCEP.

.SH AUTHOR
Andreas F. Mueller <andreas.mueller@othello.ch>

