.TH createcrl 8 "02/24/02" "OpenSCEP"
.SH NAME
createcrl \- rebuilds the certificate revokation list
.SH SYNOPSIS
.B createcrl
.SH DESCRIPTION
.B createcrl
rebuilds the certficate revokation list, and stores it in the
LDAP directory.

.SH VERSION
This page documents
.B createrl
as it appears in version 0.4.1 of OpenSCEP.

.SH AUTHOR
Andreas F. Mueller <andreas.mueller@othello.ch>

