.TH updatecrl 8 "02/24/02" "OpenSCEP"
.SH NAME
updatecrl \- add a certificate to the CRL
.SH SYNOPSIS
.B updatecrl
.I transid
.SH DESCRIPTION
.B Updatecrl
finds the certificate based on the transaction id 
.I transid
and revokes it.

.SH VERSION
This page documents
.B updatecrl
as it appears in version 0.4.1 of OpenSCEP.

.SH AUTHOR
Andreas F. Mueller <andreas.mueller@othello.ch>

