#! /bin/sh
#
# request script for the package installation of OpenSCEP
#
# (c) 2001 Dr. Andreas Mueller, Beratung und Entwicklung
#
# $Id: request,v 1.3 2001/04/04 23:36:38 afm Exp $
#
trap 'exit 3' 15
outfile=${1}

# ask for the owner of the CA directory
CAOWNER=nobody
haveowner=0
while [ ${haveowner} != 1 ]
do
	/usr/bin/echo "who shall be the owner of the CA: [${CAOWNER}] \c"
	read owner
	if [ -n "${owner}" ]
	then
		if grep "^${owner}:" /etc/passwd >/dev/null
		then
			CAOWNER=${owner}
			haveowner=1
		else
			echo unknown owner: ${owner}
		fi
	else
		haveowner=1
	fi
done
/usr/bin/echo "using owner \"${owner}\""

# ask for the group of the CA directory
CAGROUP=nogroup
havegroup=0
while [ ${havegroup} != 1 ]
do
	/usr/bin/echo "what shall be the group of the CA: [${CAGROUP}] \c"
	read group
	if [ -n "${group}" ]
	then
		if grep "^${group}:" /etc/group >/dev/null
		then
			CAGROUP=${group}
			havegroup=1
		else
			echo unknown group: ${group}
		fi
	else
		havegroup=1
	fi
done
/usr/bin/echo "using group \"${group}\""

# prepare the output of the request script
cat >${outfile} <<EOF
OWNER=${CAOWNER}
GROUP=${CAGROUP}
EOF

exit 0
